# Generated by Django 4.2 on 2023-04-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tag_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
