# Generated by Django 4.2 on 2023-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_task_assignee_alter_task_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
